import Link from "next/link";
import ThemeToggler from "../components/themetoggle";
import { StarIcon } from "@heroicons/react/24/solid";
import "../styles/globals.css";


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <head>
        <title>Starlight</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="transition-color duration-300 m-0 dark:bg-slate-800 bg-white dark:text-white">
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}

function Header() {
  return (
    <header className="z-50 transition-color duration-300 bg-white bg-opacity-50 dark:bg-slate-800 dark:bg-opacity-50 fixed top-0 backdrop-blur-lg h-16 w-full px-6 md:px-12 shadow-md flex justify-center dark:text-white">
        <div className="flex items-center justify-between gap-8 md:gap-16 h-full w-full max-w-screen-2xl">
            <Link href="/">
            <div className="flex items-center gap-2 cursor-pointer">
              <StarIcon className="w-8 h-8 text-indigo-500"></StarIcon>
              <h3 className="font-normal text-xl md:text-2xl hidden sm:block">Starlight</h3>
            </div>
            </Link>
            <div className="flex-grow">Nav</div>
            <div className="flex items-center gap-4">
              <ThemeToggler/>
              <Link href="/login" className="bg-indigo-500 text-white hover:bg-indigo-600 dark:hover:bg-indigo-400 button">Sign In</Link>
            </div>
            
        </div>
    </header>
  );
}
