import Link from "next/link";
import ThemeToggler from "../components/themetoggle";
import { StarIcon } from "@heroicons/react/24/solid";
import "../styles/globals.css";
import AccountComponent from "../components/AccountComponent";
import AutoLogin from "../components/AutoLogin";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <head>
        <title>Starlight</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className="transition-color m-0 bg-white duration-300 dark:bg-slate-800 dark:text-white">
        <Header />
        <div>{children}</div>
      </body>
    </html>
  );
}

function Header() {
  return (
    <header className="transition-color fixed top-0 z-50 flex h-16 w-full justify-center bg-white bg-opacity-50 px-6 shadow-md backdrop-blur-lg duration-300 dark:bg-slate-800 dark:bg-opacity-50 dark:text-white md:px-12">
      <div className="flex h-full w-full max-w-screen-2xl items-center justify-between gap-8 md:gap-16">
        <Link href="/">
          <div className="flex cursor-pointer items-center gap-2">
            <StarIcon className="h-8 w-8 text-indigo-500" />
            <h3 className="hidden text-xl font-normal sm:block md:text-2xl">
              Starlight
            </h3>
          </div>
        </Link>
        <div className="flex-grow">Nav</div>
        <div className="flex items-center gap-4">
          <AutoLogin/>
          <ThemeToggler />
          {/*@ts-ignore */}
          <AccountComponent/>
        </div>
      </div>
    </header>
  );
}
